env:
# - GHCVER=7.4.2 # getModificationTime signature change
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.3
 - GHCVER=8.0.1
 - GHCVER=head

matrix:
  allow_failures:
   - env: GHCVER=8.0.1 # GHC bug https://ghc.haskell.org/trac/ghc/ticket/11596
   - env: GHCVER=head  # GHC bug https://ghc.haskell.org/trac/ghc/ticket/11596

script:
 - wget https://raw.github.com/ndmitchell/neil/master/travis.sh -O - --no-check-certificate --quiet | sh
