# Weeder configuration file
# https://github.com/ndmitchell/weeder
##########################

- message: Module reused between components
- message:
  - name: Weeds exported
  - identifier: withWaiterPoll
